language: scala
scala: 
  - 2.12.4

jdk:
  - oraclejdk9

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage "testOnly concrete.* -- -l concrete.SlowTest -oDF" coverageReport coverageAggregate codacyCoverage
